[package]
name = "prefetch-yarn-deps"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
backoff = "0.4.0"
data-encoding = "2.5.0"
digest = "0.10.7"
env_logger = "0.11.3"
isahc = { version = "1.7.2", default-features = false }
log = "0.4.21"
nix-nar = "0.3.0"
rayon = "1.10.0"
serde_json = "1.0.116"
yarn-lock-parser = "0.12.0"
sha2 = "0.10.8"
tempfile = "3.10.1"
url = { version = "2.5.0" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
