[tool.poetry]
name = "nixopsenv"
version = "2.0.0"
description = "NixOps 2.0"
authors = ["Adam Hoese <adam.hose@tweag.io>"]

[tool.poetry.dependencies]
python = "^3.10"
nixops = {git = "https://github.com/NixOS/nixops.git"}
nixops-aws = {git = "https://github.com/NixOS/nixops-aws.git"}
nixops-digitalocean = {git = "https://github.com/nix-community/nixops-digitalocean.git"}
nixops-encrypted-links = {git = "https://github.com/nix-community/nixops-encrypted-links.git"}
nixops-gcp = {git = "https://github.com/nix-community/nixops-gce.git"}
nixops-hercules-ci = {git = "https://github.com/hercules-ci/nixops-hercules-ci.git"}
nixops-hetzner = {git = "https://github.com/NixOS/nixops-hetzner"}
nixops-hetznercloud = {git = "https://github.com/lukebfox/nixops-hetznercloud.git"}
nixopsvbox = {git = "https://github.com/nix-community/nixops-vbox.git"}
nixops-virtd = {git = "https://github.com/nix-community/nixops-libvirtd.git"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
