[build-system]
# Minimum requirements for the build system to execute.
requires = ["poetry-core>=1.0.0", "setuptools", "wheel", "translate-toolkit"]  # PEP 508 specifications.
build-backend = "poetry.core.masonry.api"

[tool.black]
target-version = ['py37']

[tool.poetry]
name = "weblate"
version = "4.13"
description = ""
authors = ["Your Name <you@example.com>"]
license = "GPLv3+"

[tool.poetry.dependencies]
python = ">=3.7,<3.12"
translate-toolkit = ">=3.6.0,<3.8"
GitPython = ">=2.1.15,<3.2"
user-agents = ">=2.0,<2.3"
Django = {version = ">=3.2,<4.2", extras = ["argon2"]}
translation-finder = ">=2.7,<3.0"
social-auth-core = {version = "4.3.0", extras = ["openidconnect"]}
djangorestframework = ">=3.11.0,<3.14"
social-auth-app-django = "5.0.0"
django-redis = ">=4.11.0,<6.0"
django-appconf = ">=1.0.3,<1.1"
siphashc = ">=1.2,<3.0"
pyahocorasick = ">=1.4,<1.5"
borgbackup = ">=1.1.11,<1.3"
bleach = ">=3.1.1,<6.0"
charset-normalizer = ">=2.0,<3.0"
cssselect = ">=1.0.0,<1.2"
Cython = ">=0.29.14,<0.30"
diff-match-patch = "20200713"
django-compressor = ">=2.4,<5"
django-crispy-forms = ">=1.9.0,<1.15"
django-filter = ">=2.4.0,<22.0"
filelock = ">=3.7,<3.8"
hiredis = ">=1.0.1,<2.1"
html2text = ">=2019.8.11,<2020.1.17"
importlib-metadata = ">=3.6.0,<4.12"
jellyfish = ">=0.7.2,<0.10,!=0.8.3,!=0.8.4,!=0.8.5,!=0.8.6,!=0.8.7,!=0.8.8"
jsonschema = ">=4.5,<5"
lxml = ">=4.6.3,<4.10"
misaka = ">=2.1.0,<2.2"
openpyxl = ">=2.6.0,<3.1,!=3.0.2"
Pillow = ">=9.0.0,<10.0"
pycairo = ">=1.15.3"
PyGObject = ">=3.27.0"
pyicumessageformat= ">=1.0.0,<1.1"
pyparsing = ">=3.0.5,<3.1"
python-dateutil = ">=2.8.1"
python-redis-lock = ">=3.6.0,<3.8"
requests = ">=2.26.0,<2.29"
sentry-sdk = ">=0.13.0,<1.6"
weblate-language-data = ">=2022.3"
weblate-schemas = "0.7"
psycopg2 = ">=2.7.7,<2.10.0"
celery = {extras = ["redis"], version = ">=5.0.3,<5.3"}
aeidon = {version = ">=1.9.0,<1.12.0", optional = true}
"fluent.syntax" = {version = ">=0.18.1,<0.19", optional = true}
iniparse = {version = "0.5", optional = true}
phply = {version = "1.2.5", optional = true}
Pygments = ">=2.6.0,<3.0"
pygobject = ">=3.34.0"
packaging = ">=20.5,<22.0"

[tool.poetry.dev-dependencies]

