[package]
name = "engine-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
futures = "0.3.28"
reqwest = { version = "0.11.16", features = ["stream"] }
serde_json = "1.0.96"
tokio = { version = "1.27.0", features = ["fs", "macros", "process", "rt-multi-thread"] }
zip-extract = "0.1.2"

[profile.release]
lto = "thin"
