name: Basic evaluation checks

on:
  workflow_dispatch
  # pull_request:
  #   branches:
  #    - master
  #    - release-**
  # push:
  #   branches:
  #    - master
  #    - release-**
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    # we don't limit this action to only NixOS repo since the checks are cheap and useful developer feedback
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
    - uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
      with:
        # This cache is for the nixpkgs repo checks and should not be trusted or used elsewhere.
        name: nixpkgs-ci
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    # explicit list of supportedSystems is needed until aarch64-darwin becomes part of the trunk jobset
    - run: nix-build pkgs/top-level/release.nix -A release-checks --arg supportedSystems '[ "aarch64-darwin" "aarch64-linux" "x86_64-linux" "x86_64-darwin"  ]'
