name: "Check shell"

on:
  pull_request:
    paths:
      - .github/workflows/check-shell.yml
  pull_request_target:
    paths:
      - 'shell.nix'
      - 'ci/**'

permissions: {}

jobs:
  shell-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            system: x86_64-linux
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
          - runner: macos-13
            system: x86_64-darwin
          - runner: macos-14
            system: aarch64-darwin

    name: shell-check-${{ matrix.system }}
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31

      - name: Build shell
        run: nix-build ci -A shell
