name: "Check cherry-picks"
on:
  pull_request_target:
    branches:
     - 'release-**'
     - 'staging-**'
     - '!staging-next'

permissions: {}

jobs:
  check:
    name: cherry-pick-check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NixOS'
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        fetch-depth: 0
        filter: blob:none
    - name: Check cherry-picks
      env:
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        ./maintainers/scripts/check-cherry-picks.sh "$BASE_SHA" "$HEAD_SHA"
