name: "Check that maintainer list is sorted"

on:
  pull_request_target:
    paths:
      - 'maintainers/maintainer-list.nix'
permissions:
  contents: read

jobs:
  nixos:
    name: maintainer-list-check
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NixOS'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # pull_request_target checks out the base branch by default
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
          # Only these directories to perform the check
          sparse-checkout: |
            lib
            maintainers
      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          # explicitly enable sandbox
          extra_nix_config: sandbox = true
      - name: Check that maintainer-list.nix is sorted
        run: nix-instantiate --eval maintainers/scripts/check-maintainers-sorted.nix
