name: "Build NixOS manual v2"

on:
  pull_request:
    paths:
      - .github/workflows/manual-nixos-v2.yml
  pull_request_target:
    branches:
      - master
      - release-*
    paths:
      - "nixos/**"
      # Also build when the nixpkgs doc changed, since we take things like
      # the release notes and some css and js files from there.
      # See nixos/doc/manual/default.nix
      - "doc/**"
      # Build when something in lib changes
      # Since the lib functions are used to 'massage' the options before producing the manual
      - "lib/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  nixos:
    name: nixos-manual-build
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            system: x86_64-linux
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: .github/actions
      - name: Check if the PR can be merged and checkout the merge commit
        uses: ./.github/actions/get-merge-commit
        with:
          merged-as-untrusted: true

      - uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31
        with:
          extra_nix_config: sandbox = true

      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          # This cache is for the nixpkgs repo checks and should not be trusted or used elsewhere.
          name: nixpkgs-ci
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build NixOS manual
        id: build-manual
        run: nix-build untrusted/ci -A manual-nixos --argstr system ${{ matrix.system }}

      - name: Upload NixOS manual
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: nixos-manual-${{ matrix.system }}
          path: result/
          if-no-files-found: error
