[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nixos-rebuild"
version = "0.0.0"

[project.scripts]
nixos-rebuild = "nixos_rebuild:main"

[tool.setuptools.package-data]
nixos_rebuild = ["*.nix.template"]

[tool.mypy]
# `--strict` config, but explicit options to avoid breaking build when mypy is
# updated
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
# no_implicit_reexport = true
strict_equality = true
extra_checks = true

# extra options not included in `--strict`
enable_error_code = ["explicit-override", "mutable-override"]

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[tool.ruff.lint]
extend-select = [
    # ensure imports are sorted
    "I",
    # require `check` argument for `subprocess.run`
    "PLW1510",
    # check for needless exception names in raise statements
    "TRY201",
]

[tool.ruff.lint.per-file-ignores]
"tests/" = ["FA102"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = ["--import-mode=importlib"]
